### ISSUE TITLE
UI: use more horizontal space

### ISSUE THREAD

**Issue by vEnhance** [howard36/probase#59]
this is a bit ironic because i'm normally the one complaining sites are too wide, but i feel like probase is so narrow that it makes it tough to see more than a few problems on the screen at a time.
![image](https://github.com/howard36/probase/assets/3750940/790c347b-ec08-401f-8d6e-d3cfdb63a8b4)

i think my suggestion for changing the UI to be more space-efficient (at least on desktop) would be something like

- increase the width to about 80 characters a line (right now it's less than half of that);
- try to put some more metainformation to the left of the statement rather than above it (maybe sort of like what i have on blog.evanchen.cc)

![image](https://github.com/howard36/probase/assets/3750940/48c8a4ea-eaa4-4475-a049-85094b7346da)

**Comment by howard36** [comment]
Oh yeah, I left some extra space because I was planning to add more things on each side.

Left side would have a sidebar like the one on https://www.probase.app/. Right side will have all the Add Problem / Search / Filter / Sort settings, so you don't have to scroll all the way to the top to use these
